name: Welcome New Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Welcome first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Welcome @${{ github.actor }}! Thanks for opening your first issue in our repository!
            
            We appreciate you taking the time to contribute. Our team will review this soon.
            
            Please make sure you've:
            - [ ] Checked existing issues
            - [ ] Followed our contribution guidelines
          pr-message: |
            🎉 Thanks @${{ github.actor }} for your first pull request!
            
            Our maintainers will review this shortly. In the meantime:
            - [ ] Ensure CI tests pass
            - [ ] Update documentation if needed
            - [ ] Keep an eye out for review comments
            
            We appreciate your contribution! 💙
